[package]
name = "schema_macro"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
blake3 = "1.5.4"
serde = { version = "1", features = ["derive"] }
postcard = { version = "1.0.10", features = ["alloc"] }

